---
apiVersion: v1
kind: Service
metadata:
  name: compose-post-redis
  labels:
    death-star-project: social-network
    app-name: compose-post-redis
  namespace: social-network
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    death-star-project: social-network
    app-name: compose-post-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
    #annotations:
    #"sidecar.jaegertracing.io/inject": "true"
  name: compose-post-redis
  labels:
    death-star-project: social-network
    app-name: compose-post-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: compose-post-redis
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: compose-post-redis
        INPUT: compose-post-service
      name: compose-post-redis
    spec:
      containers:
      - name: compose-post-redis
        image: redis:alpine
        resources: 
          requests: 
            cpu: "1600m"
            memory: "8Gi"
      restartPolicy: Always
      # nodeName: 10.0.0.13
      # schedulerName: poseidon
