---
apiVersion: v1
kind: Service
metadata:
  name: user-mongodb
  labels:
    death-star-project: social-network
    app-name: user-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app-name: user-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongodb
  labels:
    death-star-project: social-network
    app-name: user-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: user-mongodb
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: user-mongodb
        INPUT1: user-mention-service
        INPUT2: user-service
      name: user-mongodb
    spec:
      containers:
      - name: user-mongodb
        image: poanpan/mongo:v1
        resources: 
          requests: 
            cpu: "300m"
            memory: "120Mi"
      restartPolicy: Always
      # nodeName: 10.0.0.13
      # schedulerName: poseidon
