---
apiVersion: v1
kind: Service
metadata:
  name: user-timeline-mongodb
  labels:
    death-star-project: social-network
    app-name: user-timeline-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
    name: mongo
  selector:
    death-star-project: social-network
    app-name: user-timeline-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
    #annotations:
    #"sidecar.jaegertracing.io/inject": "true"
  name: user-timeline-mongodb
  labels:
    death-star-project: social-network
    app-name: user-timeline-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: user-timeline-mongodb
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: user-timeline-mongodb
        INPUT: user-timeline-service
      name: user-timeline-mongodb
    spec:
      containers:
      - name: user-timeline-mongodb
        image: poanpan/mongo:v1
        resources: 
          requests: 
            cpu: "1600m"
            memory: "1Gi"
      restartPolicy: Always
      # nodeName: 10.0.0.13
      # schedulerName: poseidon
