---
apiVersion: v1
kind: Service
metadata:
  name: user-memcached
  labels:
    death-star-project: social-network
    app-name: user-memcached
  namespace: social-network
spec:
  ports:
  - port: 11211
  selector:
    death-star-project: social-network
    app-name: user-memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  name: user-memcached
  labels:
    death-star-project: social-network
    app-name: user-memcached
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: user-memcached
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: user-memcached
        INPUT1: user-mention-service
        INPUT2: user-service
      name: user-memcached
    spec:
      containers:
      - name: user-memcached
        image: poanpan/memcached:v1
        resources: 
          requests: 
            cpu: "600m"
            memory: "13Mi"
      restartPolicy: Always
      # nodeName: 10.0.0.13
      # schedulerName: poseidon
