#     depends_on:
      # - write-home-timeline-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: write-home-timeline-service
  labels:
    death-star-project: social-network
    app-name: write-home-timeline-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app-name: write-home-timeline-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-home-timeline-service
  labels:
    death-star-project: social-network
    app-name: write-home-timeline-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: write-home-timeline-service
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: write-home-timeline-service
        OUTPUT1: social-graph-service
        OUTPUT2: home-timeline-redis
        INPUT: write-home-timeline-rabbitmq
      name: write-home-timeline-service
    spec:
      containers:
      - name: write-home-timeline-service
        image: poanpan/social-network-microservices:v1
        command: ["WriteHomeTimelineService"]
        resources: 
          requests: 
            cpu: "1300m"
            memory: "13Mi"
      restartPolicy: Always
      # nodeName: 10.0.0.13
      # TODO: need init-container
      # schedulerName: poseidon
