---
apiVersion: v1
kind: Service
metadata:
  name: url-shorten-mongodb
  labels:
    death-star-project: social-network
    app-name: url-shorten-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app-name: url-shorten-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  name: url-shorten-mongodb
  labels:
    death-star-project: social-network
    app-name: url-shorten-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: url-shorten-mongodb
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app-name: url-shorten-mongodb
        INPUT: url-shorten-service
      name: url-shorten-mongodb
    spec:
      containers:
      - name: url-shorten-mongodb
        image: poanpan/mongo:v1
        resources: 
          requests: 
            cpu: "700m"
            memory: "3.2Gi"
      restartPolicy: Always
      # nodeName: 10.0.0.13
      # schedulerName: poseidon
