apiVersion: v1
kind: PersistentVolume
metadata: 
  name: deathstar-sn-gl-nfs-pv
  labels: 
    pv: deathstar-sn-gl-nfs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home1/root/DeathStarBench/socialNetwork/gen-lua
    server: 10.0.0.252