apiVersion: v1
kind: PersistentVolume
metadata: 
  name: deathstar-sn-mf-nfs-pv
  labels: 
    pv: deathstar-sn-mf-nfs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home1/root/DeathStarBench/socialNetwork/media-frontend
    server: 10.0.0.252